import { AddressService } from './address/createAddressService.js';
import { AdminService } from './admin/createAdminService.js';
import { AllergyService } from './allergy/createAllergyService.js';
import { BookingRequestAllergyService } from './booking-request-allergy/createBookingRequestService.js';
import { BookingRequestService } from './booking-request/createBookingRequestService.js';
import { CategoryService } from './category/createCategoryService.js';
import { ChatMessageService } from './chat-message/createChatMessageService.js';
import { ConfiguredMenuService } from './configured-menu/createConfiguredMenuService.js';
import { CookLanguageService } from './cook-language/createCookLanguageService.js';
import { CookRatingService } from './cook-rating/createCookRatingService.js';
import { CookSpecificFeeService } from './cook-specific-fee/createCookSpecificFeeService.js';
import { CookVisitService } from './cook-visit/createCookVisitService.js';
import { CookService } from './cook/createCookService.js';
import { CourseService } from './course/createCourseService.js';
import { CustomerFeeUpdateService } from './customer-fee-update/createCustomerFeeUpdateService.js';
import { EmailAddressUpdateService } from './email-address-update/createEmailAddressUpdateService.js';
import { FavoriteCookService } from './favorite-cook/createFavoriteCookService.js';
import { GlobalBookingRequestService } from './global-booking-request/createGlobalBookingRequestService.js';
import { KitchenService } from './kitchen/createKitchenService.js';
import { LanguageService } from './language/createLanguageService.js';
import { MealOptionService } from './meal-option/createMealOptionService.js';
import { MealVisitService } from './meal-visit/createMealVisitService.js';
import { MealService } from './meal/createMealService.js';
import { MenuCategoryService } from './menu-category/createMenuCategoryService.js';
import { MenuVisitService } from './menu-visit/createMenuVisitService.js';
import { MenuService } from './menu/createMenuService.js';
import { NotificationConfigurationService } from './notification-configuration/createNotificationConfigurationService.js';
import { NotificationService } from './notification/createNotificationService.js';
import { OneTimeAccessTokenService } from './one-time-access-token/createOneTimeAccessTokenService.js';
import { PhoneNumberUpdateService } from './phone-number-update/createPhoneNumberUpdateService.js';
import { PrivacyPolicyUpdateService } from './privacy-policy-update/createPrivacyPolicyUpdateService.js';
import { PublicCookService } from './public-cook/createPublicCookService.js';
import { PublicMenuService } from './public-menu/createPublicMenuService.js';
import { PublicPrivacyPolicyUpdateService } from './public-privacy-policy-update/createPublicPrivacyPolicyUpdateService.js';
import { PublicTermsUpdateService } from './public-terms-update/createPublicTermsUpdateService.js';
import { PublicUserService } from './public-user/createPublicUserService.js';
import { SearchRequestService } from './search-request/createSearchRequestService.js';
import { SessionService } from './session/createSessionService.js';
import { TermsUpdateService } from './terms-update/createTermsUpdateService.js';
import { UserRatingService } from './user-rating/createUserRatingService.js';
import { UserService } from './user/createUserService.js';

export interface Service {
    address: AddressService;
    admin: AdminService;
    allergy: AllergyService;
    bookingRequest: BookingRequestService;
    bookingRequestAllergy: BookingRequestAllergyService;
    chatMessage: ChatMessageService;
    category: CategoryService;
    cook: CookService;
    cookLanguage: CookLanguageService;
    cookRating: CookRatingService;
    cookSpecificFee: CookSpecificFeeService;
    cookVisit: CookVisitService;
    course: CourseService;
    configuredMenu: ConfiguredMenuService;
    customerFeeUpdate: CustomerFeeUpdateService;
    emailAddressUpdate: EmailAddressUpdateService;
    favoriteCook: FavoriteCookService;
    globalBookingRequest: GlobalBookingRequestService;
    kitchen: KitchenService;
    language: LanguageService;
    menu: MenuService;
    menuCategory: MenuCategoryService;
    menuVisit: MenuVisitService;
    meal: MealService;
    mealOption: MealOptionService;
    mealVisit: MealVisitService;
    notification: NotificationService;
    notificationConfiguration: NotificationConfigurationService;
    oneTimeAccessToken: OneTimeAccessTokenService;
    phoneNumberUpdate: PhoneNumberUpdateService;
    privacyPolicyUpdate: PrivacyPolicyUpdateService;
    publicCook: PublicCookService;
    publicMenu: PublicMenuService;
    publicPrivacyPolicyUpdate: PublicPrivacyPolicyUpdateService;
    publicTermsUpdate: PublicTermsUpdateService;
    publicUser: PublicUserService;
    session: SessionService;
    searchRequest: SearchRequestService;
    termsUpdate: TermsUpdateService;
    user: UserService;
    userRating: UserRatingService;
}
